"""empty message

Revision ID: 287c4baf3baf
Revises: 
Create Date: 2020-06-27 14:26:25.714296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287c4baf3baf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('duedate', sa.String(), nullable=False),
    sa.Column('mobileno', sa.String(), nullable=False),
    sa.Column('custID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('custID')
    )
    op.create_index(op.f('ix_customers_custID'), 'customers', ['custID'], unique=False)
    op.create_index(op.f('ix_customers_mobileno'), 'customers', ['mobileno'], unique=True)
    op.create_table('transactions',
    sa.Column('refID', sa.String(), nullable=True),
    sa.Column('transactionID', sa.String(), nullable=True),
    sa.Column('custID', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_transactions_refID'), 'transactions', ['refID'], unique=False)
    op.create_table('users',
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_users_key'), 'users', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_refID'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_customers_mobileno'), table_name='customers')
    op.drop_index(op.f('ix_customers_custID'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
